service: m3u-bot

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
